import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import {createHash} from 'node:crypto';
const project = new URL('../', import.meta.url);
const read = path => fs.readFile(new URL(path, project), 'utf8');
const code = await read('public/admin/editor.js');
const template = JSON.parse(await read('templates/admin-config.yml'));
const demo = JSON.parse(await read('public/admin/demo-config.json'));
const vendor = await fs.readFile(new URL('public/admin/vendor/decap-cms-3.15.1.js', project));
assert.equal(createHash('sha256').update(vendor).digest('hex'),'952395b66c20e29ee3989e2924de6a5e31e2e2c0ec8daa1c5fa7cf79286b1e06');
assert.equal(template.backend.name, 'github');
assert.equal(template.backend.open_authoring, true);
assert.equal(template.backend.auth_scope, 'public_repo');
assert.equal(template.publish_mode, 'editorial_workflow');
assert.deepEqual(demo.collections, template.collections);
assert.equal(demo.backend.name, 'test-repo');
const fields = template.collections[0].fields;
assert.deepEqual(fields.map(f=>f.name), ['id','youtubeId','url','thumbnailUrl','title','originalTitle','date','type','durationSeconds','topics','brief','summaryMarkdown','published']);
assert.equal(fields.find(f=>f.name==='published').default,false);
const thumbnail = fields.find(f=>f.name==='thumbnailUrl');
assert.equal(thumbnail.required,false);
const thumbnailPattern = new RegExp(thumbnail.pattern[0]);
assert.ok(thumbnailPattern.test(''));
assert.ok(thumbnailPattern.test('https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg'));
assert.ok(!thumbnailPattern.test('https://evil.example/thumbnail.jpg'));
assert.ok(!thumbnailPattern.test('http://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg'));
assert.equal(template.collections[0].folder,'content/talks');
assert.equal(template.collections[0].format,'json');
assert.equal(template.collections[0].slug,'{{fields.id}}');
async function run({hostname='example.org',search='',ok=true,config=template,loadError=false}) {
 const elements = new Map();
 for(const id of ['editor-status','status-message','setup-help','demo-link','preview-notice']) elements.set(id,{hidden:id!=='editor-status',textContent:''});
 const initialized=[]; const loaded=[]; const requests=[];
 const window={CMS:{init:options=>initialized.push(options)}};
 const document={getElementById:id=>elements.get(id),createElement:()=>({}),body:{classList:{add(){}}},head:{append:script=>{loaded.push(script.src);queueMicrotask(()=>loadError?script.onerror():script.onload());}}};
 vm.runInNewContext(code,{location:{hostname,search},window,document,URLSearchParams,AbortController,setTimeout,clearTimeout,SyntaxError,fetch:async url=>{requests.push(url);return {ok,json:async()=>structuredClone(config)}}});
 await new Promise(resolve=>setImmediate(resolve));
 return {elements,initialized,loaded,requests};
}
let r=await run({ok:false});
assert.match(r.elements.get('status-message').textContent,/not connected/);
assert.equal(r.elements.get('setup-help').hidden,false);
assert.equal(r.loaded.length,0);
r=await run({});
assert.match(r.elements.get('status-message').textContent,/not configured/);
assert.equal(r.initialized.length,0);
const live=JSON.parse(JSON.stringify(template).replaceAll('__GITHUB_REPOSITORY__','owner/dhamma-library').replaceAll('__SITE_URL__','https://example.org'));
r=await run({config:live});
assert.equal(r.initialized[0].config.backend.name,'github');
assert.equal(r.initialized[0].config.load_config_file,false);
assert.equal(r.elements.get('editor-status').hidden,true);
assert.deepEqual(r.loaded,['./vendor/decap-cms-3.15.1.js']);
r=await run({search:'?demo=1',config:demo});
assert.equal(r.requests.length,0);
assert.match(r.elements.get('status-message').textContent,/only on localhost/);
for(const hostname of ['localhost','127.0.0.1','[::1]']) {
 r=await run({hostname,search:'?demo=1',config:demo});
 assert.equal(r.initialized[0].config.backend.name,'test-repo');
 assert.deepEqual(r.requests,['./demo-config.json']);
 assert.equal(r.elements.get('preview-notice').hidden,false);
}
r=await run({config:live,loadError:true});
assert.match(r.elements.get('status-message').textContent,/could not be loaded/);
assert.equal(r.elements.get('setup-help').hidden,false);
console.log('Admin bootstrap, configuration, preview isolation, and pinned vendor integrity checks passed. Browser draft-save and production OAuth are separate integration checks.');
